import type { SpeakingScenarioDefinition } from "./types";

export const speakingScenarioLibraryData: SpeakingScenarioDefinition[] = [
  {
    id: "daily-morning-routine",
    slug: "morning-routine",
    title: "Talk About Your Morning Routine",
    description:
      "Practice describing the things you normally do after waking up and before starting your day.",
    category: "daily_life",
    difficulty: "beginner",
    cefrRange: {
      min: "A1",
      max: "A2",
    },
    conversationType: "guided_conversation",
    learnerRole: "You are talking about your normal morning routine.",
    coachRole:
      "You are a friendly conversation partner asking simple questions about the learner's morning.",
    objective: "Practice describing routines, times, everyday actions, and simple sequences.",
    setting: "A relaxed everyday conversation.",
    skills: ["answering_questions", "describing"],
    suggestedOpening: "What do you usually do first after you wake up?",
    tags: ["routine", "morning", "daily-life"],
    estimatedMinutes: 6,
    active: true,
  },

  {
    id: "daily-weekend-plans",
    slug: "weekend-plans",
    title: "Make Weekend Plans",
    description: "Practice discussing plans and deciding what to do during the weekend.",
    category: "daily_life",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "guided_conversation",
    learnerRole: "You are discussing your weekend plans with a friend.",
    coachRole: "You are a friend asking about plans and suggesting activities.",
    objective: "Practice talking about future plans, preferences, and simple suggestions.",
    setting: "A casual conversation between friends.",
    skills: ["answering_questions", "making_suggestions", "giving_opinions"],
    suggestedOpening: "Do you have any plans for this weekend?",
    tags: ["weekend", "plans", "friends"],
    estimatedMinutes: 7,
    active: true,
  },

  {
    id: "daily-order-food",
    slug: "ordering-food",
    title: "Order Food at a Restaurant",
    description:
      "Practice ordering a meal, asking simple questions, and responding to restaurant staff.",
    category: "daily_life",
    difficulty: "elementary",
    cefrRange: {
      min: "A1",
      max: "B1",
    },
    conversationType: "role_play",
    learnerRole: "You are a customer ordering a meal.",
    coachRole: "You are a restaurant server.",
    objective: "Practice ordering food, making requests, and asking about menu items.",
    setting: "A casual restaurant.",
    skills: ["requesting", "asking_questions", "clarifying"],
    suggestedOpening: "Hello. Are you ready to order?",
    tags: ["restaurant", "food", "ordering"],
    estimatedMinutes: 7,
    active: true,
  },

  {
    id: "travel-airport-check-in",
    slug: "airport-check-in",
    title: "Airport Check-In",
    description: "Practice checking in for a flight and answering common airline questions.",
    category: "travel",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "role_play",
    learnerRole: "You are a passenger checking in for an international flight.",
    coachRole: "You are an airline check-in agent.",
    objective:
      "Practice giving travel information, answering questions, and making simple requests.",
    setting: "An airline check-in counter at an international airport.",
    skills: ["answering_questions", "requesting", "clarifying"],
    suggestedOpening: "Good morning. May I see your passport and ticket, please?",
    tags: ["airport", "flight", "travel"],
    estimatedMinutes: 8,
    active: true,
  },

  {
    id: "travel-hotel-check-in",
    slug: "hotel-check-in",
    title: "Check Into a Hotel",
    description:
      "Practice checking into a hotel, confirming a reservation, and asking about facilities.",
    category: "travel",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "role_play",
    learnerRole: "You are a traveler arriving at a hotel.",
    coachRole: "You are the hotel receptionist.",
    objective:
      "Practice confirming reservations, answering questions, and requesting hotel information.",
    setting: "A hotel reception desk.",
    skills: ["requesting", "answering_questions", "asking_questions"],
    suggestedOpening: "Welcome. Do you have a reservation with us?",
    tags: ["hotel", "reservation", "travel"],
    estimatedMinutes: 8,
    active: true,
  },

  {
    id: "travel-ask-directions",
    slug: "asking-for-directions",
    title: "Ask for Directions",
    description:
      "Practice asking how to reach a place and checking that you understood the directions.",
    category: "travel",
    difficulty: "beginner",
    cefrRange: {
      min: "A1",
      max: "A2",
    },
    conversationType: "role_play",
    learnerRole: "You are a visitor trying to find a destination.",
    coachRole: "You are a local person giving directions.",
    objective: "Practice location vocabulary, asking questions, and confirming directions.",
    setting: "A city street.",
    skills: ["asking_questions", "clarifying"],
    suggestedOpening: "Hi. You look a little lost. Can I help you?",
    tags: ["directions", "city", "travel"],
    estimatedMinutes: 6,
    active: true,
  },

  {
    id: "travel-flight-problem",
    slug: "delayed-flight",
    title: "Handle a Delayed Flight",
    description: "Practice asking for information and possible solutions after a flight delay.",
    category: "travel",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "problem_solving",
    learnerRole: "You are a passenger whose flight has been significantly delayed.",
    coachRole: "You are an airline customer-service representative.",
    objective:
      "Practice explaining concerns, asking for alternatives, and clarifying travel arrangements.",
    setting: "An airport customer-service desk.",
    skills: ["problem_solving", "clarifying", "requesting", "negotiating"],
    suggestedOpening: "Hello. I understand your flight has been delayed. How can I help?",
    tags: ["airport", "delay", "problem-solving"],
    estimatedMinutes: 10,
    active: true,
  },

  {
    id: "work-first-day",
    slug: "first-day-at-work",
    title: "Your First Day at Work",
    description:
      "Practice introducing yourself and having simple conversations with new colleagues.",
    category: "work",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "simulation",
    learnerRole: "You are starting a new job.",
    coachRole: "You are one of the learner's new colleagues.",
    objective: "Practice introductions, small talk, and basic workplace communication.",
    setting: "An office on the learner's first day.",
    skills: ["small_talk", "answering_questions", "asking_questions"],
    suggestedOpening: "Hi, you must be new here. I'm Alex. Nice to meet you.",
    tags: ["work", "office", "introduction"],
    estimatedMinutes: 7,
    active: true,
  },

  {
    id: "work-team-meeting",
    slug: "team-meeting",
    title: "Participate in a Team Meeting",
    description: "Practice giving an update, responding to colleagues, and discussing next steps.",
    category: "work",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "simulation",
    learnerRole: "You are a team member giving an update during a meeting.",
    coachRole: "You are the meeting leader and another team member.",
    objective: "Practice concise updates, professional questions, and discussing work priorities.",
    setting: "A weekly team meeting.",
    skills: ["professional_communication", "explaining", "answering_questions", "clarifying"],
    suggestedOpening: "Let's start with your update. How is your current work going?",
    tags: ["meeting", "office", "professional"],
    estimatedMinutes: 10,
    active: true,
  },

  {
    id: "work-deadline-negotiation",
    slug: "discussing-a-deadline",
    title: "Discuss a Difficult Deadline",
    description: "Practice explaining a workload problem and discussing a realistic deadline.",
    category: "work",
    difficulty: "upper_intermediate",
    cefrRange: {
      min: "B2",
      max: "C1",
    },
    conversationType: "problem_solving",
    learnerRole: "You are an employee who believes the current project deadline is unrealistic.",
    coachRole: "You are the learner's manager.",
    objective:
      "Practice explaining constraints, negotiating professionally, and proposing solutions.",
    setting: "A private workplace discussion.",
    skills: ["professional_communication", "explaining", "negotiating", "problem_solving"],
    suggestedOpening: "You asked to talk about the project deadline. What's concerning you?",
    tags: ["deadline", "manager", "negotiation"],
    estimatedMinutes: 12,
    active: true,
  },

  {
    id: "education-class-introduction",
    slug: "introduce-yourself-in-class",
    title: "Introduce Yourself in Class",
    description:
      "Practice giving a short introduction to classmates and answering simple questions.",
    category: "education",
    difficulty: "beginner",
    cefrRange: {
      min: "A1",
      max: "A2",
    },
    conversationType: "simulation",
    learnerRole: "You are a new student introducing yourself.",
    coachRole: "You are a classmate meeting the learner for the first time.",
    objective:
      "Practice personal introductions, basic information, and simple follow-up questions.",
    setting: "The first day of an English class.",
    skills: ["describing", "answering_questions", "asking_questions"],
    suggestedOpening: "Hi! I'm Sam. What's your name?",
    tags: ["school", "introduction", "student"],
    estimatedMinutes: 6,
    active: true,
  },

  {
    id: "education-ask-teacher",
    slug: "asking-a-teacher-for-help",
    title: "Ask a Teacher for Help",
    description:
      "Practice explaining what you do not understand and asking useful study questions.",
    category: "education",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "role_play",
    learnerRole: "You are a student who needs help understanding an assignment.",
    coachRole: "You are the learner's teacher.",
    objective: "Practice asking for clarification and explaining learning difficulties.",
    setting: "After class.",
    skills: ["asking_questions", "clarifying", "explaining"],
    suggestedOpening: "You wanted to ask me something about the assignment?",
    tags: ["teacher", "assignment", "education"],
    estimatedMinutes: 7,
    active: true,
  },

  {
    id: "education-group-project",
    slug: "group-project-discussion",
    title: "Plan a Group Project",
    description:
      "Practice sharing ideas, dividing responsibilities, and agreeing on a project plan.",
    category: "education",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "problem_solving",
    learnerRole: "You are a student working on a group assignment.",
    coachRole: "You are another member of the project group.",
    objective: "Practice making suggestions, discussing responsibilities, and reaching agreement.",
    setting: "A study room before a group project begins.",
    skills: ["making_suggestions", "agreeing_disagreeing", "problem_solving"],
    suggestedOpening: "We should decide how we're going to divide the project. What do you think?",
    tags: ["group-project", "study", "planning"],
    estimatedMinutes: 10,
    active: true,
  },

  {
    id: "social-meet-new-person",
    slug: "meeting-someone-new",
    title: "Meet Someone New",
    description: "Practice introducing yourself and maintaining a friendly first conversation.",
    category: "social",
    difficulty: "beginner",
    cefrRange: {
      min: "A1",
      max: "A2",
    },
    conversationType: "role_play",
    learnerRole: "You are meeting someone for the first time.",
    coachRole: "You are another guest at a social gathering.",
    objective: "Practice introductions, simple questions, and everyday small talk.",
    setting: "A small social gathering.",
    skills: ["small_talk", "asking_questions", "answering_questions"],
    suggestedOpening: "Hi, I don't think we've met before. I'm Jamie.",
    tags: ["social", "introduction", "small-talk"],
    estimatedMinutes: 6,
    active: true,
  },

  {
    id: "social-invitation",
    slug: "invite-a-friend",
    title: "Invite a Friend Somewhere",
    description: "Practice inviting someone, discussing availability, and agreeing on a plan.",
    category: "social",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "role_play",
    learnerRole: "You want to invite a friend to do something together.",
    coachRole: "You are the learner's friend.",
    objective: "Practice invitations, scheduling, suggestions, and responding naturally.",
    setting: "An informal conversation between friends.",
    skills: ["requesting", "making_suggestions", "clarifying"],
    suggestedOpening: "Hey! What are you doing this weekend?",
    tags: ["friends", "invitation", "plans"],
    estimatedMinutes: 7,
    active: true,
  },

  {
    id: "social-discuss-opinion",
    slug: "discuss-an-opinion",
    title: "Discuss Different Opinions",
    description:
      "Practice expressing an opinion and respectfully responding to a different point of view.",
    category: "social",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "open_discussion",
    learnerRole:
      "You are discussing an everyday topic with someone who may have a different opinion.",
    coachRole: "You are a conversation partner who respectfully presents another perspective.",
    objective: "Practice giving reasons, agreeing and disagreeing, and asking follow-up questions.",
    setting: "A friendly discussion.",
    skills: ["giving_opinions", "agreeing_disagreeing", "explaining"],
    suggestedOpening: "Do you think people spend too much time on their phones these days?",
    tags: ["opinions", "discussion", "social"],
    estimatedMinutes: 10,
    active: true,
  },

  {
    id: "shopping-buy-clothes",
    slug: "buying-clothes",
    title: "Buy Clothes in a Store",
    description: "Practice asking about size, color, price, and availability while shopping.",
    category: "shopping_services",
    difficulty: "beginner",
    cefrRange: {
      min: "A1",
      max: "A2",
    },
    conversationType: "role_play",
    learnerRole: "You are shopping for clothes.",
    coachRole: "You are a store assistant.",
    objective: "Practice asking about products, prices, sizes, and preferences.",
    setting: "A clothing store.",
    skills: ["asking_questions", "requesting", "clarifying"],
    suggestedOpening: "Hello. Can I help you find something?",
    tags: ["shopping", "clothes", "store"],
    estimatedMinutes: 7,
    active: true,
  },

  {
    id: "shopping-return-product",
    slug: "returning-a-product",
    title: "Return a Product",
    description:
      "Practice explaining a problem with a purchase and requesting a reasonable solution.",
    category: "shopping_services",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "problem_solving",
    learnerRole: "You are a customer returning a product that does not work properly.",
    coachRole: "You are a customer-service representative.",
    objective:
      "Practice explaining problems, providing details, and requesting a refund or replacement.",
    setting: "A store customer-service desk.",
    skills: ["explaining", "requesting", "problem_solving", "negotiating"],
    suggestedOpening: "Hello. What seems to be the problem with the item?",
    tags: ["return", "customer-service", "shopping"],
    estimatedMinutes: 9,
    active: true,
  },

  {
    id: "shopping-phone-support",
    slug: "customer-support-call",
    title: "Call Customer Support",
    description: "Practice explaining a service problem clearly over the phone.",
    category: "shopping_services",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "simulation",
    learnerRole: "You are calling customer support about a service problem.",
    coachRole: "You are the support representative.",
    objective:
      "Practice explaining problems, answering verification questions, and clarifying solutions.",
    setting: "A customer-support phone call.",
    skills: ["explaining", "clarifying", "problem_solving"],
    suggestedOpening: "Thank you for calling customer support. How can I help you today?",
    tags: ["support", "phone", "service"],
    estimatedMinutes: 10,
    active: true,
  },

  {
    id: "health-doctor-appointment",
    slug: "doctor-appointment",
    title: "Talk to a Doctor About Symptoms",
    description:
      "Practice clearly describing ordinary symptoms and answering basic questions during a medical appointment.",
    category: "health_wellness",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "role_play",
    learnerRole: "You are a patient describing a minor health concern.",
    coachRole:
      "You are a clinician asking communication-focused questions without diagnosing or prescribing.",
    objective: "Practice describing symptoms, duration, and basic health information clearly.",
    setting: "A routine medical appointment.",
    skills: ["describing", "answering_questions", "clarifying"],
    suggestedOpening: "What brings you in today?",
    tags: ["health", "doctor", "symptoms"],
    estimatedMinutes: 8,
    active: true,
  },

  {
    id: "health-fitness-goals",
    slug: "talk-about-fitness-goals",
    title: "Talk About Fitness Goals",
    description:
      "Practice discussing exercise habits, personal goals, and general lifestyle preferences.",
    category: "health_wellness",
    difficulty: "elementary",
    cefrRange: {
      min: "A2",
      max: "B1",
    },
    conversationType: "guided_conversation",
    learnerRole: "You are discussing your general fitness goals.",
    coachRole:
      "You are a conversation partner asking non-medical questions about exercise and habits.",
    objective: "Practice describing routines, preferences, goals, and progress.",
    setting: "A general conversation about fitness.",
    skills: ["describing", "explaining", "answering_questions"],
    suggestedOpening: "What would you like to improve about your fitness?",
    tags: ["fitness", "exercise", "goals"],
    estimatedMinutes: 8,
    active: true,
  },

  {
    id: "problem-missing-order",
    slug: "missing-online-order",
    title: "Solve a Missing Order Problem",
    description: "Practice contacting a company when an online order has not arrived.",
    category: "problem_solving",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "problem_solving",
    learnerRole: "You are a customer whose online order should have arrived several days ago.",
    coachRole: "You are the company's customer-service representative.",
    objective:
      "Practice explaining a problem, giving relevant information, and discussing solutions.",
    setting: "An online retailer's support conversation.",
    skills: ["explaining", "problem_solving", "clarifying", "negotiating"],
    suggestedOpening: "Hello. How can I help you with your order today?",
    tags: ["delivery", "order", "support"],
    estimatedMinutes: 10,
    active: true,
  },

  {
    id: "problem-roommate",
    slug: "roommate-problem",
    title: "Resolve a Roommate Problem",
    description: "Practice discussing a household disagreement calmly and finding a fair solution.",
    category: "problem_solving",
    difficulty: "upper_intermediate",
    cefrRange: {
      min: "B2",
      max: "C1",
    },
    conversationType: "problem_solving",
    learnerRole: "You want to discuss a recurring household issue with your roommate.",
    coachRole: "You are the learner's roommate.",
    objective:
      "Practice raising concerns politely, listening to another perspective, and negotiating a solution.",
    setting: "A shared apartment.",
    skills: ["explaining", "agreeing_disagreeing", "negotiating", "problem_solving"],
    suggestedOpening: "You said you wanted to talk about something at home. What's going on?",
    tags: ["roommate", "conflict", "negotiation"],
    estimatedMinutes: 12,
    active: true,
  },

  {
    id: "problem-misunderstanding",
    slug: "clarify-a-misunderstanding",
    title: "Clear Up a Misunderstanding",
    description:
      "Practice explaining what happened when two people understood a situation differently.",
    category: "problem_solving",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "problem_solving",
    learnerRole: "You want to clear up a misunderstanding with another person.",
    coachRole: "You are the other person and initially understand the situation differently.",
    objective: "Practice clarification, explanation, and respectful disagreement.",
    setting: "A private conversation.",
    skills: ["clarifying", "explaining", "agreeing_disagreeing"],
    suggestedOpening: "I think we may have misunderstood each other earlier.",
    tags: ["misunderstanding", "clarification", "communication"],
    estimatedMinutes: 9,
    active: true,
  },

  {
    id: "public-bank-account",
    slug: "ask-about-a-bank-account",
    title: "Ask About Opening a Bank Account",
    description:
      "Practice asking general questions about opening a bank account and required documents.",
    category: "public_situations",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "role_play",
    learnerRole: "You are asking a bank employee for general information about opening an account.",
    coachRole:
      "You are a bank employee explaining general account requirements without giving financial advice.",
    objective:
      "Practice asking formal questions, clarifying requirements, and understanding procedures.",
    setting: "A bank branch.",
    skills: ["asking_questions", "clarifying", "professional_communication"],
    suggestedOpening: "Good morning. What can I help you with today?",
    tags: ["bank", "documents", "public-services"],
    estimatedMinutes: 9,
    active: true,
  },

  {
    id: "public-train-ticket",
    slug: "buy-a-train-ticket",
    title: "Buy a Train Ticket",
    description: "Practice asking about routes, departure times, prices, and ticket options.",
    category: "public_situations",
    difficulty: "beginner",
    cefrRange: {
      min: "A1",
      max: "A2",
    },
    conversationType: "role_play",
    learnerRole: "You need to buy a train ticket.",
    coachRole: "You are a ticket-office employee.",
    objective: "Practice asking about transportation schedules, prices, and destinations.",
    setting: "A train station ticket counter.",
    skills: ["requesting", "asking_questions", "clarifying"],
    suggestedOpening: "Hello. Where would you like to travel today?",
    tags: ["train", "ticket", "transport"],
    estimatedMinutes: 6,
    active: true,
  },

  {
    id: "public-government-office",
    slug: "ask-about-a-public-service",
    title: "Ask About a Public Service",
    description: "Practice asking a public-office employee about a general administrative process.",
    category: "public_situations",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "role_play",
    learnerRole: "You are asking for information about a general administrative service.",
    coachRole: "You are a public-service employee providing general procedural information.",
    objective: "Practice formal questions, explaining your purpose, and clarifying required steps.",
    setting: "A public-service information desk.",
    skills: ["asking_questions", "clarifying", "professional_communication"],
    suggestedOpening: "Good morning. What service do you need information about?",
    tags: ["public-service", "office", "documents"],
    estimatedMinutes: 9,
    active: true,
  },

  {
    id: "social-storytelling",
    slug: "tell-an-interesting-story",
    title: "Tell an Interesting Story",
    description:
      "Practice telling a clear personal story with a beginning, development, and ending.",
    category: "social",
    difficulty: "intermediate",
    cefrRange: {
      min: "B1",
      max: "B2",
    },
    conversationType: "guided_conversation",
    learnerRole: "You are telling the conversation partner about an interesting experience.",
    coachRole: "You are an engaged listener asking natural follow-up questions.",
    objective: "Practice organizing events, describing details, and maintaining listener interest.",
    setting: "A relaxed conversation.",
    skills: ["storytelling", "describing", "answering_questions"],
    suggestedOpening: "Tell me about something memorable that happened to you.",
    tags: ["storytelling", "experience", "conversation"],
    estimatedMinutes: 10,
    active: true,
  },

  {
    id: "work-present-idea",
    slug: "present-an-idea",
    title: "Present an Idea to Your Team",
    description: "Practice explaining an idea clearly and responding to questions or concerns.",
    category: "work",
    difficulty: "advanced",
    cefrRange: {
      min: "C1",
      max: "C2",
    },
    conversationType: "simulation",
    learnerRole: "You are presenting a proposal or improvement idea to colleagues.",
    coachRole: "You are a colleague asking thoughtful questions and raising reasonable concerns.",
    objective:
      "Practice structured explanation, persuasion, clarification, and professional discussion.",
    setting: "A professional team discussion.",
    skills: ["professional_communication", "explaining", "giving_opinions", "clarifying"],
    suggestedOpening: "You said you have an idea you'd like the team to consider. Please go ahead.",
    tags: ["presentation", "idea", "professional"],
    estimatedMinutes: 12,
    active: true,
  },

  {
    id: "education-debate",
    slug: "academic-discussion",
    title: "Take Part in an Academic Discussion",
    description:
      "Practice developing an argument, responding to counterarguments, and explaining reasoning.",
    category: "education",
    difficulty: "advanced",
    cefrRange: {
      min: "C1",
      max: "C2",
    },
    conversationType: "open_discussion",
    learnerRole: "You are participating in a university-style discussion.",
    coachRole: "You are another participant who asks challenging but respectful questions.",
    objective: "Practice structured arguments, nuanced opinions, and responding to opposing views.",
    setting: "A university seminar discussion.",
    skills: ["giving_opinions", "agreeing_disagreeing", "explaining", "clarifying"],
    suggestedOpening:
      "Let's discuss whether technology has improved the quality of modern education overall.",
    tags: ["academic", "discussion", "argument"],
    estimatedMinutes: 15,
    active: true,
  },

  {
    id: "free-general-conversation",
    slug: "free-conversation",
    title: "Free Conversation",
    description: "Have a natural English conversation without a predefined role-play situation.",
    category: "free_conversation",
    difficulty: "intermediate",
    cefrRange: {
      min: "A1",
      max: "C2",
    },
    conversationType: "open_discussion",
    learnerRole: null,
    coachRole: null,
    objective:
      "Practice natural spoken English by discussing topics chosen during the conversation.",
    setting: null,
    skills: ["asking_questions", "answering_questions", "small_talk"],
    suggestedOpening: null,
    tags: ["free", "conversation", "general"],
    estimatedMinutes: 10,
    active: true,
  },
];
