import type { AssessmentQuestion } from "@/lib/types";

export const GRAMMAR_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "g1",
    skill: "grammar",
    difficulty: "easy",
    type: "multiple_choice",
    prompt: "She ______ to school every day.",
    options: ["go", "goes", "going", "gone"],
    answer_index: 1,
  },
  {
    id: "g2",
    skill: "grammar",
    difficulty: "easy",
    type: "multiple_choice",
    prompt: "I saw ______ elephant at the zoo.",
    options: ["a", "an", "the", "—"],
    answer_index: 1,
  },
  {
    id: "g3",
    skill: "grammar",
    difficulty: "easy",
    type: "fill_blank",
    prompt: "The book is ______ the table.",
    answer: "on",
  },
  {
    id: "g4",
    skill: "grammar",
    difficulty: "medium",
    type: "multiple_choice",
    prompt: "By the time we arrived, they ______ dinner.",
    options: ["finish", "finished", "had finished", "have finished"],
    answer_index: 2,
  },
  {
    id: "g5",
    skill: "grammar",
    difficulty: "medium",
    type: "sentence_correction",
    prompt: "Choose the correct sentence.",
    options: [
      "He don't like coffee.",
      "He doesn't likes coffee.",
      "He doesn't like coffee.",
      "He not like coffee.",
    ],
    answer_index: 2,
  },
  {
    id: "g6",
    skill: "grammar",
    difficulty: "medium",
    type: "multiple_choice",
    prompt: "If it rains tomorrow, we ______ at home.",
    options: ["stay", "will stay", "would stay", "stayed"],
    answer_index: 1,
  },
  {
    id: "g7",
    skill: "grammar",
    difficulty: "hard",
    type: "multiple_choice",
    prompt: "The report ______ by the manager yesterday.",
    options: ["reviewed", "was reviewed", "has reviewed", "is reviewing"],
    answer_index: 1,
  },
  {
    id: "g8",
    skill: "grammar",
    difficulty: "hard",
    type: "sentence_correction",
    prompt: "Choose the correct sentence.",
    options: [
      "If I would have known, I would have called.",
      "If I had known, I would have called.",
      "If I knew, I would called.",
      "If I have known, I would call.",
    ],
    answer_index: 1,
  },
  {
    id: "g9",
    skill: "grammar",
    difficulty: "hard",
    type: "fill_blank",
    prompt: "Neither the students nor the teacher ______ ready.",
    answer: "was",
    accepted: ["is"],
  },
];