import type { AssessmentQuestion } from "@/lib/types";

export const VOCABULARY_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "v1",
    skill: "vocabulary",
    difficulty: "easy",
    type: "multiple_choice",
    prompt: "Which word means 'a place where you live'?",
    options: ["Home", "Car", "Book", "Cloud"],
    answer_index: 0,
  },
  {
    id: "v2",
    skill: "vocabulary",
    difficulty: "easy",
    type: "synonym",
    prompt: "Choose the synonym.",
    word: "Happy",
    options: ["Sad", "Joyful", "Angry", "Tired"],
    answer_index: 1,
  },
  {
    id: "v3",
    skill: "vocabulary",
    difficulty: "medium",
    type: "fill_blank",
    prompt: "She was so ______ that she couldn't stop smiling.",
    answer: "delighted",
    accepted: ["happy", "thrilled", "pleased"],
  },
  {
    id: "v4",
    skill: "vocabulary",
    difficulty: "medium",
    type: "match",
    prompt: "Match each word to its meaning.",
    pairs: [
      { left: "Reluctant", right: "Unwilling" },
      { left: "Generous", right: "Giving freely" },
      { left: "Fragile", right: "Easily broken" },
      { left: "Vivid", right: "Very bright" },
    ],
  },
  {
    id: "v5",
    skill: "vocabulary",
    difficulty: "medium",
    type: "synonym",
    prompt: "Choose the synonym.",
    word: "Rapid",
    options: ["Slow", "Quiet", "Quick", "Heavy"],
    answer_index: 2,
  },
  {
    id: "v6",
    skill: "vocabulary",
    difficulty: "hard",
    type: "multiple_choice",
    prompt: "'Ubiquitous' most nearly means:",
    options: ["Rare", "Everywhere", "Ancient", "Hidden"],
    answer_index: 1,
  },
  {
    id: "v7",
    skill: "vocabulary",
    difficulty: "hard",
    type: "fill_blank",
    prompt: "The evidence was ______; nobody could deny it.",
    answer: "irrefutable",
    accepted: ["undeniable", "conclusive"],
  },
  {
    id: "v8",
    skill: "vocabulary",
    difficulty: "hard",
    type: "synonym",
    prompt: "Choose the synonym.",
    word: "Meticulous",
    options: ["Careless", "Careful", "Bored", "Loud"],
    answer_index: 1,
  },
];
